name: Update version with Maven

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: Update type
        required: true
        type: choice
        options:
          # `major` not yet supported
          - minor
          - bugfix

jobs:
  update-version:
    name: Update version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit --allow-empty -m "Empty commit"
          git commit --allow-empty -S -m "Should be verified"
          git push
