name: Update version with Maven
# - validate that there is no dependency on snapshot
# - update version to non-snapshot
# - commit and tag
# - update version to snapshot
# - push changes

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: Update type
        required: true
        type: choice
        options:
          # `major` not yet supported
          - minor
          - bugfix

jobs:
  update-version:
    name: Update version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Create a branch
        run: |
          git checkout -b issues/temp
          git push origin issues/temp
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
#      - name: Run Maven release:prepare
#        run: |
#          echo ${{ inputs.update_type }}
#          if [ ${{ inputs.update_type }} == "minor" ]; then
#            mvn -B -U -DdryRun=true release:prepare -DtagNameFormat=@{project.version} -DprojectVersionPolicyId=SemVerVersionPolicy
#          elif [ ${{ inputs.update_type }} == "bugfix" ]; then
#            mvn -B -U -DdryRun=true release:prepare -DtagNameFormat=@{project.version}
#          else
#            echo "Not supported type: ${{ inputs.update_type }}"
#            exit 1
#          fi
      - name: create pull request
        run: gh pr create --base develop --title 'Merge test' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
